WebEscuelaMVC/Models/Aula.cs
using System.ComponentModel.DataAnnotations;
using WebEscuelaMVC.Validations;

namespace WebEscuelaMVC.Models
{
    public class Aula
    {
        public int Id { get; set; }

        [Required]
        [NumeroMayor100]
        public int Numero { get; set; }

        [Required]
        public string Estado { get; set; }


    }
}

WebEscuelaMVC/Controllers/AulaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using WebEscuelaMVC.Data;
using WebEscuelaMVC.Models;

namespace WebEscuelaMVC.Controllers
{
    public class AulaController : Controller
    {

        private readonly EscuelaDBMVCContext context;

        public AulaController(EscuelaDBMVCContext context)
        {
            this.context = context;

        }
        public IActionResult Index()
        {
            var aulas = context.Aulas.ToList();
            return View(aulas);
        }




        private Aula TraerUna(int id)
        {
            return context.Aulas.Find(id);
        }

        //Create
        [HttpGet]
        public ActionResult Create()
        {

            Aula aula = new Aula();

            return View("Register", aula);

        }


        [HttpPost]
        public ActionResult Create(Aula aula)
        {
            if (ModelState.IsValid)
            {
                context.Aulas.Add(aula);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aula);
        }


        //GetDetails


        [HttpGet]
        public ActionResult Details(int id)
        {
            Aula aula = TraerUna(id);
            if (aula == null)
            {
                return NotFound();
            }
            else
            {
                return View("detalle", aula);
            }


        }


        //Edit

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var aula = TraerUna(id);

            if (aula == null)
            {
                return NotFound();
            }
            else
            {
                return View(aula);
            }
        }



        [HttpPost]
        [ActionName("Edit")]

        public ActionResult EditConfirmed(Aula aula)
        {
            if (ModelState.IsValid)
            {
                context.Entry(aula).State = EntityState.Modified;

                context.SaveChanges();

                return RedirectToAction("Index");

            }
            else
            {
                return View(aula);
            }
        }




        //Delete

        [HttpGet]


        public ActionResult Delete(int id)
        {
            var aula = TraerUna(id);

            if (aula == null)
            {
                return NotFound();
            }

            else
            {
                return View("Delete",aula);
            }

        }



        [ActionName("Delete")]
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            var aula = TraerUna(id);
            if (aula == null)
            {
                return NotFound();
            }
            else
            {
                context.Aulas.Remove(aula);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

        }
 
    }
}

WebEscuelaMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace WebEscuelaMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Nombre = "Bienvenido al sistema de Alumnos";
            ViewBag.Fecha = DateTime.Now;
            return View();
        }
    }
}

WebEscuelaMVC/Views/Aula/Delete.cshtml
@model WebEscuelaMVC.Models.Aula


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2> Aula @Model.Numero </h2>
    <p>¿Desea eliminar esta aula?</p>

    @using (Html.BeginForm("Delete", "Aula", FormMethod.Post))
    {
        <div>
            <span>@Html.DisplayNameFor(model => model.Numero)</span>
            <span>@Html.DisplayFor(model => model.Numero)</span>
        </div>

        <div>
            <span>@Html.DisplayNameFor(model => model.Estado)</span>
            <span>@Html.DisplayFor(model => model.Estado)</span>
        </div>

     

        <input type="submit" action="Delete" />

        @Html.ActionLink("Volver", "Index", "Aula")

    }

</body>
</html>

WebEscuelaMVC/Views/Aula/Edit.cshtml
@model WebEscuelaMVC.Models.Aula

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <h1>Editar aula</h1>

    @using (Html.BeginForm("Edit", "Aula", FormMethod.Post))
    {
        <p>
            @Html.LabelFor(model => model.Numero)
            @Html.TextBoxFor(model => model.Numero)
            @Html.ValidationMessageFor(model => model.Numero)
        </p>

        <p>
            @Html.LabelFor(model => model.Estado)
            @Html.TextBoxFor(model => model.Estado)
            @Html.ValidationMessageFor(model => model.Estado)
        </p>

        <input type="submit" action="Edit" />

        @Html.ActionLink("Volver a ver aulas", "Index", "Aula")

    }

</body>
</html>

WebEscuelaMVC/Views/Aula/Index.cshtml
@model IEnumerable<WebEscuelaMVC.Models.Aula>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @Html.ActionLink("Nuevo", "Create", "Aula")

    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Numero)</th>
            <th>@Html.DisplayNameFor(model => model.Estado)</th>
            
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Numero)</td>
                <td>@Html.DisplayFor(modelItem => item.Estado)</td>
              
                <td>
                    @Html.ActionLink("Detalle", "Details", "Aula", new{id = item.Id})
                    @Html.ActionLink("Eliminar", "Delete", "Aula", new{id = item.Id})
                    @Html.ActionLink("Editar", "Edit", "Aula", new{id = item.Id})
                </td>
            </tr>
         
        }
    </table>
</body>
</html>

WebEscuelaMVC/Views/Aula/Register.cshtml
@model WebEscuelaMVC.Models.Aula

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <h1>Agregar aula</h1>

    @using (Html.BeginForm("Create", "Aula", FormMethod.Post))
    {
        <p>
            @Html.LabelFor(model => model.Numero)
            @Html.TextBoxFor(model => model.Numero)
            @Html.ValidationMessageFor(model => model.Numero)
        </p>

        <p>
            @Html.LabelFor(model => model.Estado)
            @Html.TextBoxFor(model => model.Estado)
            @Html.ValidationMessageFor(model => model.Estado)
        </p>

     

        <input type="submit" action="Create" />

        @Html.ActionLink("Volver a ver aulas", "Index", "Aula")

    }

</body>
</html>

WebEscuelaMVC/Views/Aula/detalle.cshtml
@model WebEscuelaMVC.Models.Aula

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>detalle</title>
</head>
<body>
    <h2>Ver Detalle Aula</h2>
    @Html.ActionLink("Volver a index", "Index", "Aula")

    <p>
        @Html.DisplayNameFor(model => model.Numero)
        @Html.DisplayFor(model => model.Numero)
    </p>

    <p>
        @Html.DisplayNameFor(model => model.Estado)
        @Html.DisplayFor(model => model.Estado)
    </p>
</body>
</html>

WebEscuelaMVC/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>@ViewBag.Nombre</h2>
    <h3>@ViewBag.Fecha</h3>

    @Html.ActionLink("Ir a Aulas", "Index", "Aula")
</body>
</html>